# Generated by Django 2.2.3 on 2019-07-23 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='blog_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogContent'),
        ),
    ]
