# Generated by Django 2.2.3 on 2019-07-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190723_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='url',
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='content_type',
            field=models.CharField(choices=[('image', 'image'), ('code', 'code'), ('text', 'text')], max_length=100),
        ),
    ]
