# Generated by Django 2.2.4 on 2019-09-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190728_0423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='blogcontent',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='blogentry',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='blogsection',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['created_date']},
        ),
        migrations.AddField(
            model_name='blogentry',
            name='topic',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='blog/img/uploads'),
        ),
    ]
