# Generated by Django 2.2.4 on 2019-09-03 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190902_0443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogsection',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='blogsection',
            unique_together={('blog', 'order')},
        ),
    ]
