# Generated by Django 2.2.4 on 2019-09-03 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190903_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Order must be greater than or equal to zero.')], verbose_name='ordering of sections within a blog'),
        ),
    ]
